apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-mongo-pacman-6eyc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-mongo-pacman-6eyc
    app.kubernetes.io/part-of: mp-user-env-var
  name: mongo-mongo-pacman-6eyc
  namespace: jduimovich-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongo-mongo-pacman-6eyc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongo-mongo-pacman-6eyc
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:5236bc58a0a6ecaec6ac813cc3f0b73703bf411c87a5e8c796011ef3a2b99ad3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
