apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-mongo-pacman-6eyc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-mongo-pacman-6eyc
    app.kubernetes.io/part-of: mp-user-env-var
  name: mongo-mongo-pacman-6eyc
  namespace: jduimovich-tenant
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/instance: mongo-mongo-pacman-6eyc
status:
  loadBalancer: {}
