apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-mongo-pacman-lvoj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-mongo-pacman-lvoj
    app.kubernetes.io/part-of: mp-user-env-var
  name: frontend-mongo-pacman-lvoj
  namespace: jduimovich-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: frontend-mongo-pacman-lvoj
status:
  loadBalancer: {}
